import turtle
t = turtle.Pen()
t.hideturtle()
t.speed(11)
t.pensize(0)
turtle.bgcolor('black')
t.pencolor('yellow')
t.left(180)
# t.width(1)
while True:
    t.pendown()
    # t.forward(10)
    # t.right(45)
    # t.forward(10)
    # t.left(90)
    # t.forward(10)
    # t.right(45)
    t.circle(120, 180)
    t.left(75)
